### ISSUE TITLE
check if db is not running and provide graceful msg. 

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-cloud#222]
File "/cm/cloudmesh-cmd5/cloudmesh/shell/shell.py", line 938, in main
    stop = cmd.onecmd(command)
  File "/cm/cloudmesh-cmd5/cloudmesh/shell/shell.py", line 366, in onecmd
    return func(arg)
  File "/cm/cloudmesh-cmd5/cloudmesh/shell/command.py", line 103, in new
    func(instance, args, arguments)
  File "/Users//Desktop/github/cloudmesh-community/cm/cloudmesh-cloud/cloudmesh/vm/command/vm.py", line 634, in do_vm
    vms = provider.create(**parameters)
  File "/cm/cloudmesh-cloud/cloudmesh/mongo/DataBaseDecorator.py", line 87, in wrapper
    current = f(*args, **kwargs)
  File "/cm/cloudmesh-cloud/cloudmesh/compute/vm/Provider.py", line 172, in create
    duplicates += database.find(collection=f'{cloud}-node', query=query)
  File "/cm/cloudmesh-cloud/cloudmesh/mongo/CmDatabase.py", line 371, in find
    add(_collection)
  File "/cm/cloudmesh-cloud/cloudmesh/mongo/CmDatabase.py", line 360, in add
    for entry in entries:
  File "/python3.7/site-packages/pymongo/cursor.py", line 1225, in next
    if len(self.__data) or self._refresh():
  File "/python3.7/site-packages/pymongo/cursor.py", line 1117, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/python3.7/site-packages/pymongo/mongo_client.py", line 1598, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/python3.7/site-packages/pymongo/mongo_client.py", line 1551, in __start_session
    server_session = self._get_server_session()
  File "/python3.7/site-packages/pymongo/mongo_client.py", line 1584, in _get_server_session
    return self._topology.get_server_session()
  File "/python3.7/site-packages/pymongo/topology.py", line 429, in get_server_session
    None)
  File "/python3.7/site-packages/pymongo/topology.py", line 200, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: 127.0.0.1:27017: [Errno 61] Connection refused

**Comment by laszewsk** [comment]
cms vm boot
ERROR: MongoDB service is not running ...
ERROR: MongoDB service is not running ...
ERROR: MongoDB service is not running ...
ERROR: MongoDB service is not running ...
ERROR: MongoDB service is not running ...
ERROR: MongoDB service is not running ...
ERROR: MongoDB service is not running ...
ERROR: MongoDB service is not running ...
ERROR: MongoDB service is not running ...
ERROR: MongoDB service is not running ...
ERROR: MongoDB service is not running ...
ERROR: MongoDB service is not running ...
ERROR: MongoDB service is not running ...
ERROR: MongoDB service is not running ...
ERROR: MongoDB service is not running ...
ERROR: MongoDB service is not running ...
ERROR: MongoDB service is not running ...
ERROR: MongoDB service is not running ...
ERROR: MongoDB service is not running ...
ERROR: MongoDB service is not running ...
'CmDatabase' object has no attribute 'db'
Traceback (most recent call last):
  File "/Users/grey/Desktop/github/cloudmesh-community/cm/cloudmesh-cmd5/cloudmesh/shell/shell.py", line 366, in onecmd
    return func(arg)
  File "/Users/grey/Desktop/github/cloudmesh-community/cm/cloudmesh-cmd5/cloudmesh/shell/command.py", line 103, in new
    func(instance, args, arguments)
  File "/Users/grey/Desktop/github/cloudmesh-community/cm/cloudmesh-cloud/cloudmesh/vm/command/vm.py", line 634, in do_vm
    vms = provider.create(**parameters)
  File "/Users/grey/Desktop/github/cloudmesh-community/cm/cloudmesh-cloud/cloudmesh/mongo/DataBaseDecorator.py", line 87, in wrapper
    current = f(*args, **kwargs)
  File "/Users/grey/Desktop/github/cloudmesh-community/cm/cloudmesh-cloud/cloudmesh/compute/vm/Provider.py", line 172, in create
    duplicates += database.find(collection=f'{cloud}-node', query=query)
  File "/Users/grey/Desktop/github/cloudmesh-community/cm/cloudmesh-cloud/cloudmesh/mongo/CmDatabase.py", line 373, in find
    add(_collection)
  File "/Users/grey/Desktop/github/cloudmesh-community/cm/cloudmesh-cloud/cloudmesh/mongo/CmDatabase.py", line 357, in add
    col = self.db[collection]
AttributeError: 'CmDatabase' object has no attribute 'db'

**Comment by laszewsk** [comment]
do 

cms stop
cms vm boot

to test this
