### ISSUE TITLE
Windows error executing command 'admin mongo install'

### ISSUE THREAD

**Issue by brianfunk3** [cloudmesh/cloudmesh-cloud#236]
Log is below. This is after a fresh pull of cloud from git and changing the cloudmesh.yaml autoinstall in Mongo to True

C:\Users\Brian/.cloudmesh/mongodb
MongoDB is not installed in ~/.cloudmesh/mongodb
ERROR: executing command 'admin mongo install'
======================================================================
"'url'"
"'url'"
Traceback (most recent call last):
  File "C:\Users\Brian\ENV3\cm\cloudmesh-cmd5\cloudmesh\shell\shell.py", line 938, in main
    stop = cmd.onecmd(command)
  File "C:\Users\Brian\ENV3\cm\cloudmesh-cmd5\cloudmesh\shell\shell.py", line 366, in onecmd
    return func(arg)
  File "C:\Users\Brian\ENV3\cm\cloudmesh-cmd5\cloudmesh\shell\command.py", line 103, in new
    func(instance, args, arguments)
  File "C:\Users\Brian\ENV3\cm\cloudmesh-cloud\cloudmesh\admin\command\admin.py", line 118, in do_admin
    r = installer.install(sudo=sudo)
  File "C:\Users\Brian\ENV3\cm\cloudmesh-cloud\cloudmesh\mongo\MongoDBController.py", line 104, in install
    self.windows()
  File "C:\Users\Brian\ENV3\cm\cloudmesh-cloud\cloudmesh\mongo\MongoDBController.py", line 171, in windows
    """.format(**self.data)
KeyError: "'url'"

**Comment by laszewsk** [comment]
you ahve an old yaml file.
make sure you have done cloudmesh-installer git pull
rename the old yamlfile to cloudmesh.yaml-old
than call 
cms help
that you have a new yaml filr

**Comment by Vafa-Andalibi** [comment]
fixed in 5623d81
