### ISSUE TITLE
cms vm ping may not work

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-cloud#312]
cms vm ping

on openstack

ERROR: problem executing subprocess

Trace:
Traceback (most recent call last):
      File "/Users/grey/Desktop/github/cloudmesh-community/cm/cloudmesh-common/cloudmesh/common/Shell.py", line 1016, in execute
        result = subprocess.check_output(
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 411, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 512, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['ping', '-c', '1', '129.114.25.20']' returned non-zero exit status 2.

**Comment by laszewsk** [comment]
This seems to be an error when we upload the icmp rule in secgroup add

**Comment by laszewsk** [comment]
fixed, the protocoll type was for testing set to tcp
